apiVersion: v1
kind: Pod
metadata:
  name: api-back-kube
  namespace: backend
  labels: 
    app: api-back-kube
spec:
  runtimeClassName: kata
  serviceAccountName: pod-manager
  containers:
    - name: api-back
      image: n0n3me/browsermania:v1
      ports:
        - containerPort: 3000 
