apiVersion: v1
kind: Service
metadata:
  name: service-backend
  namespace: backend
spec:
  selector:
    app: api-back-kube
  ports:
    - protocol: TCP
      nodePort: 30000
      port: 3000
      targetPort: 3000
  type: NodePort
