name: Rust-analise
on:
  push:
    branches:
    - '*'

env:
  CARGO_TERM_COLOR: always
  secret: ${{ secrets.GITHUB_TOKEN }}

#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v4
#    - name: Run Clippy
#      run: cargo clippy --all-targets --all-features

jobs:
 semgrep_rust:
    name: semgrep_rust
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: fmt
        run: cargo fmt --check
      - name : change source
        run: source /home/runner-admin/semgrep/bin/activate
      - name: Analyse semgrep 1
        run: semgrep --config "p/rust" .
 
 remove_dep:
    needs: semgrep_rust
    name: demove_dep
    runs-on: self-hosted
    continue-on-error: true
    steps: 
     - name: cargo-vet-init
       run: cargo vet init
     - name: cargo-vet
       run: cargo vet
 third-part:
    needs: remove_dep
    name: third-part
    runs-on: self-hosted
    continue-on-error: true
    steps: 
     - name: cargo-machete
       run: cargo machete
 audit:
    needs: third-part
    name: audit-code
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - name: cargo-audit
        run: cargo audit
 clippy:
    needs: audit
    name: clippy-code
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - name: Clippy-analyse
        run: cargo clippy
 compile:
    needs: clippy
    name: compile-code-for-dockerfile
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - name: Build-static
        run: cargo build --release --target x86_64-unknown-linux-musl
